// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransferRequestProto.proto
package com.intellif.feign.protobuf;

public final class TransferRequestProto {
    private TransferRequestProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface TransferRequestMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:TransferRequestMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string uuid = 1;</code>
         */
        boolean hasUuid();

        /**
         * <code>required string uuid = 1;</code>
         */
        java.lang.String getUuid();

        /**
         * <code>required string uuid = 1;</code>
         */
        com.google.protobuf.ByteString
        getUuidBytes();

        /**
         * <code>required string method = 2;</code>
         */
        boolean hasMethod();

        /**
         * <code>required string method = 2;</code>
         */
        java.lang.String getMethod();

        /**
         * <code>required string method = 2;</code>
         */
        com.google.protobuf.ByteString
        getMethodBytes();

        /**
         * <code>optional string url = 3;</code>
         */
        boolean hasUrl();

        /**
         * <code>optional string url = 3;</code>
         */
        java.lang.String getUrl();

        /**
         * <code>optional string url = 3;</code>
         */
        com.google.protobuf.ByteString
        getUrlBytes();

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */
        int getHeadersCount();

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */
        boolean containsHeaders(
                java.lang.String key);

        /**
         * Use {@link #getHeadersMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>
        getHeaders();

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */
        java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>
        getHeadersMap();

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */

        TransferRequestProto.TransferRequestMessage.ListString getHeadersOrDefault(
                java.lang.String key,
                TransferRequestProto.TransferRequestMessage.ListString defaultValue);

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */

        TransferRequestProto.TransferRequestMessage.ListString getHeadersOrThrow(
                java.lang.String key);

        /**
         * <code>optional bytes body = 5;</code>
         */
        boolean hasBody();

        /**
         * <code>optional bytes body = 5;</code>
         */
        com.google.protobuf.ByteString getBody();
    }

    /**
     * Protobuf type {@code TransferRequestMessage}
     */
    public static final class TransferRequestMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:TransferRequestMessage)
            TransferRequestMessageOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use TransferRequestMessage.newBuilder() to construct.
        private TransferRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TransferRequestMessage() {
            uuid_ = "";
            method_ = "";
            url_ = "";
            body_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new TransferRequestMessage();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private TransferRequestMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            uuid_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            method_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            url_ = bs;
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                                headers_ = com.google.protobuf.MapField.newMapField(
                                        HeadersDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000008;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>
                                    headers__ = input.readMessage(
                                    HeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            headers_.getMutableMap().put(
                                    headers__.getKey(), headers__.getValue());
                            break;
                        }
                        case 42: {
                            bitField0_ |= 0x00000008;
                            body_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TransferRequestProto.internal_static_TransferRequestMessage_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 4:
                    return internalGetHeaders();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TransferRequestProto.internal_static_TransferRequestMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TransferRequestProto.TransferRequestMessage.class, TransferRequestProto.TransferRequestMessage.Builder.class);
        }

        public interface ListStringOrBuilder extends
                // @@protoc_insertion_point(interface_extends:TransferRequestMessage.ListString)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>repeated string pojo = 1;</code>
             */
            java.util.List<java.lang.String>
            getPojoList();

            /**
             * <code>repeated string pojo = 1;</code>
             */
            int getPojoCount();

            /**
             * <code>repeated string pojo = 1;</code>
             */
            java.lang.String getPojo(int index);

            /**
             * <code>repeated string pojo = 1;</code>
             */
            com.google.protobuf.ByteString
            getPojoBytes(int index);
        }

        /**
         * Protobuf type {@code TransferRequestMessage.ListString}
         */
        public static final class ListString extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:TransferRequestMessage.ListString)
                ListStringOrBuilder {
            private static final long serialVersionUID = 0L;

            // Use ListString.newBuilder() to construct.
            private ListString(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }

            private ListString() {
                pojo_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            }

            @java.lang.Override
            @SuppressWarnings({"unused"})
            protected java.lang.Object newInstance(
                    UnusedPrivateParameter unused) {
                return new ListString();
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }

            private ListString(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                    pojo_ = new com.google.protobuf.LazyStringArrayList();
                                    mutable_bitField0_ |= 0x00000001;
                                }
                                pojo_.add(bs);
                                break;
                            }
                            default: {
                                if (!parseUnknownField(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    if (((mutable_bitField0_ & 0x00000001) != 0)) {
                        pojo_ = pojo_.getUnmodifiableView();
                    }
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TransferRequestProto.internal_static_TransferRequestMessage_ListString_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TransferRequestProto.internal_static_TransferRequestMessage_ListString_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TransferRequestProto.TransferRequestMessage.ListString.class, TransferRequestProto.TransferRequestMessage.ListString.Builder.class);
            }

            public static final int POJO_FIELD_NUMBER = 1;
            private com.google.protobuf.LazyStringList pojo_;

            /**
             * <code>repeated string pojo = 1;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getPojoList() {
                return pojo_;
            }

            /**
             * <code>repeated string pojo = 1;</code>
             */
            public int getPojoCount() {
                return pojo_.size();
            }

            /**
             * <code>repeated string pojo = 1;</code>
             */
            public java.lang.String getPojo(int index) {
                return pojo_.get(index);
            }

            /**
             * <code>repeated string pojo = 1;</code>
             */
            public com.google.protobuf.ByteString
            getPojoBytes(int index) {
                return pojo_.getByteString(index);
            }

            private byte memoizedIsInitialized = -1;

            @java.lang.Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @java.lang.Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                for (int i = 0; i < pojo_.size(); i++) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pojo_.getRaw(i));
                }
                unknownFields.writeTo(output);
            }

            @java.lang.Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                {
                    int dataSize = 0;
                    for (int i = 0; i < pojo_.size(); i++) {
                        dataSize += computeStringSizeNoTag(pojo_.getRaw(i));
                    }
                    size += dataSize;
                    size += 1 * getPojoList().size();
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof TransferRequestProto.TransferRequestMessage.ListString)) {
                    return super.equals(obj);
                }
                TransferRequestProto.TransferRequestMessage.ListString other = (TransferRequestProto.TransferRequestMessage.ListString) obj;

                if (!getPojoList()
                        .equals(other.getPojoList())) return false;
                if (!unknownFields.equals(other.unknownFields)) return false;
                return true;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                if (getPojoCount() > 0) {
                    hash = (37 * hash) + POJO_FIELD_NUMBER;
                    hash = (53 * hash) + getPojoList().hashCode();
                }
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static TransferRequestProto.TransferRequestMessage.ListString parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            @java.lang.Override
            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(TransferRequestProto.TransferRequestMessage.ListString prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            @java.lang.Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code TransferRequestMessage.ListString}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:TransferRequestMessage.ListString)
                    TransferRequestProto.TransferRequestMessage.ListStringOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return TransferRequestProto.internal_static_TransferRequestMessage_ListString_descriptor;
                }

                @java.lang.Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return TransferRequestProto.internal_static_TransferRequestMessage_ListString_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    TransferRequestProto.TransferRequestMessage.ListString.class, TransferRequestProto.TransferRequestMessage.ListString.Builder.class);
                }

                // Construct using TransferRequestProto.TransferRequestMessage.ListString.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }

                @java.lang.Override
                public Builder clear() {
                    super.clear();
                    pojo_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000001);
                    return this;
                }

                @java.lang.Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return TransferRequestProto.internal_static_TransferRequestMessage_ListString_descriptor;
                }

                @java.lang.Override
                public TransferRequestProto.TransferRequestMessage.ListString getDefaultInstanceForType() {
                    return TransferRequestProto.TransferRequestMessage.ListString.getDefaultInstance();
                }

                @java.lang.Override
                public TransferRequestProto.TransferRequestMessage.ListString build() {
                    TransferRequestProto.TransferRequestMessage.ListString result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @java.lang.Override
                public TransferRequestProto.TransferRequestMessage.ListString buildPartial() {
                    TransferRequestProto.TransferRequestMessage.ListString result = new TransferRequestProto.TransferRequestMessage.ListString(this);
                    int from_bitField0_ = bitField0_;
                    if (((bitField0_ & 0x00000001) != 0)) {
                        pojo_ = pojo_.getUnmodifiableView();
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.pojo_ = pojo_;
                    onBuilt();
                    return result;
                }

                @java.lang.Override
                public Builder clone() {
                    return super.clone();
                }

                @java.lang.Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.setField(field, value);
                }

                @java.lang.Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }

                @java.lang.Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }

                @java.lang.Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, java.lang.Object value) {
                    return super.setRepeatedField(field, index, value);
                }

                @java.lang.Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.addRepeatedField(field, value);
                }

                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof TransferRequestProto.TransferRequestMessage.ListString) {
                        return mergeFrom((TransferRequestProto.TransferRequestMessage.ListString) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(TransferRequestProto.TransferRequestMessage.ListString other) {
                    if (other == TransferRequestProto.TransferRequestMessage.ListString.getDefaultInstance())
                        return this;
                    if (!other.pojo_.isEmpty()) {
                        if (pojo_.isEmpty()) {
                            pojo_ = other.pojo_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensurePojoIsMutable();
                            pojo_.addAll(other.pojo_);
                        }
                        onChanged();
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final boolean isInitialized() {
                    return true;
                }

                @java.lang.Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    TransferRequestProto.TransferRequestMessage.ListString parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (TransferRequestProto.TransferRequestMessage.ListString) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private int bitField0_;

                private com.google.protobuf.LazyStringList pojo_ = com.google.protobuf.LazyStringArrayList.EMPTY;

                private void ensurePojoIsMutable() {
                    if (!((bitField0_ & 0x00000001) != 0)) {
                        pojo_ = new com.google.protobuf.LazyStringArrayList(pojo_);
                        bitField0_ |= 0x00000001;
                    }
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public com.google.protobuf.ProtocolStringList
                getPojoList() {
                    return pojo_.getUnmodifiableView();
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public int getPojoCount() {
                    return pojo_.size();
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public java.lang.String getPojo(int index) {
                    return pojo_.get(index);
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public com.google.protobuf.ByteString
                getPojoBytes(int index) {
                    return pojo_.getByteString(index);
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public Builder setPojo(
                        int index, java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePojoIsMutable();
                    pojo_.set(index, value);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public Builder addPojo(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePojoIsMutable();
                    pojo_.add(value);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public Builder addAllPojo(
                        java.lang.Iterable<java.lang.String> values) {
                    ensurePojoIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, pojo_);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public Builder clearPojo() {
                    pojo_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string pojo = 1;</code>
                 */
                public Builder addPojoBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePojoIsMutable();
                    pojo_.add(value);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @java.lang.Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:TransferRequestMessage.ListString)
            }

            // @@protoc_insertion_point(class_scope:TransferRequestMessage.ListString)
            private static final TransferRequestProto.TransferRequestMessage.ListString DEFAULT_INSTANCE;

            static {
                DEFAULT_INSTANCE = new TransferRequestProto.TransferRequestMessage.ListString();
            }

            public static TransferRequestProto.TransferRequestMessage.ListString getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            @java.lang.Deprecated
            public static final com.google.protobuf.Parser<ListString>
                    PARSER = new com.google.protobuf.AbstractParser<ListString>() {
                @java.lang.Override
                public ListString parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new ListString(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<ListString> parser() {
                return PARSER;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<ListString> getParserForType() {
                return PARSER;
            }

            @java.lang.Override
            public TransferRequestProto.TransferRequestMessage.ListString getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

        }

        private int bitField0_;
        public static final int UUID_FIELD_NUMBER = 1;
        private volatile java.lang.Object uuid_;

        /**
         * <code>required string uuid = 1;</code>
         */
        public boolean hasUuid() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required string uuid = 1;</code>
         */
        public java.lang.String getUuid() {
            java.lang.Object ref = uuid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    uuid_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string uuid = 1;</code>
         */
        public com.google.protobuf.ByteString
        getUuidBytes() {
            java.lang.Object ref = uuid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                uuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int METHOD_FIELD_NUMBER = 2;
        private volatile java.lang.Object method_;

        /**
         * <code>required string method = 2;</code>
         */
        public boolean hasMethod() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required string method = 2;</code>
         */
        public java.lang.String getMethod() {
            java.lang.Object ref = method_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    method_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string method = 2;</code>
         */
        public com.google.protobuf.ByteString
        getMethodBytes() {
            java.lang.Object ref = method_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                method_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int URL_FIELD_NUMBER = 3;
        private volatile java.lang.Object url_;

        /**
         * <code>optional string url = 3;</code>
         */
        public boolean hasUrl() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional string url = 3;</code>
         */
        public java.lang.String getUrl() {
            java.lang.Object ref = url_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    url_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string url = 3;</code>
         */
        public com.google.protobuf.ByteString
        getUrlBytes() {
            java.lang.Object ref = url_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                url_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int HEADERS_FIELD_NUMBER = 4;

        private static final class HeadersDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>newDefaultInstance(
                                    TransferRequestProto.internal_static_TransferRequestMessage_HeadersEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                    TransferRequestProto.TransferRequestMessage.ListString.getDefaultInstance());
        }

        private com.google.protobuf.MapField<
                java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> headers_;

        private com.google.protobuf.MapField<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>
        internalGetHeaders() {
            if (headers_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        HeadersDefaultEntryHolder.defaultEntry);
            }
            return headers_;
        }

        public int getHeadersCount() {
            return internalGetHeaders().getMap().size();
        }

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */

        public boolean containsHeaders(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetHeaders().getMap().containsKey(key);
        }

        /**
         * Use {@link #getHeadersMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> getHeaders() {
            return getHeadersMap();
        }

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */

        public java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> getHeadersMap() {
            return internalGetHeaders().getMap();
        }

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */

        public TransferRequestProto.TransferRequestMessage.ListString getHeadersOrDefault(
                java.lang.String key,
                TransferRequestProto.TransferRequestMessage.ListString defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> map =
                    internalGetHeaders().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
         */

        public TransferRequestProto.TransferRequestMessage.ListString getHeadersOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> map =
                    internalGetHeaders().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int BODY_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString body_;

        /**
         * <code>optional bytes body = 5;</code>
         */
        public boolean hasBody() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>optional bytes body = 5;</code>
         */
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasUuid()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMethod()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, url_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetHeaders(),
                            HeadersDefaultEntryHolder.defaultEntry,
                            4);
            if (((bitField0_ & 0x00000008) != 0)) {
                output.writeBytes(5, body_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, url_);
            }
            for (java.util.Map.Entry<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> entry
                    : internalGetHeaders().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>
                        headers__ = HeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, headers__);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, body_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TransferRequestProto.TransferRequestMessage)) {
                return super.equals(obj);
            }
            TransferRequestProto.TransferRequestMessage other = (TransferRequestProto.TransferRequestMessage) obj;

            if (hasUuid() != other.hasUuid()) return false;
            if (hasUuid()) {
                if (!getUuid()
                        .equals(other.getUuid())) return false;
            }
            if (hasMethod() != other.hasMethod()) return false;
            if (hasMethod()) {
                if (!getMethod()
                        .equals(other.getMethod())) return false;
            }
            if (hasUrl() != other.hasUrl()) return false;
            if (hasUrl()) {
                if (!getUrl()
                        .equals(other.getUrl())) return false;
            }
            if (!internalGetHeaders().equals(
                    other.internalGetHeaders())) return false;
            if (hasBody() != other.hasBody()) return false;
            if (hasBody()) {
                if (!getBody()
                        .equals(other.getBody())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasUuid()) {
                hash = (37 * hash) + UUID_FIELD_NUMBER;
                hash = (53 * hash) + getUuid().hashCode();
            }
            if (hasMethod()) {
                hash = (37 * hash) + METHOD_FIELD_NUMBER;
                hash = (53 * hash) + getMethod().hashCode();
            }
            if (hasUrl()) {
                hash = (37 * hash) + URL_FIELD_NUMBER;
                hash = (53 * hash) + getUrl().hashCode();
            }
            if (!internalGetHeaders().getMap().isEmpty()) {
                hash = (37 * hash) + HEADERS_FIELD_NUMBER;
                hash = (53 * hash) + internalGetHeaders().hashCode();
            }
            if (hasBody()) {
                hash = (37 * hash) + BODY_FIELD_NUMBER;
                hash = (53 * hash) + getBody().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TransferRequestProto.TransferRequestMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TransferRequestProto.TransferRequestMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TransferRequestProto.TransferRequestMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TransferRequestProto.TransferRequestMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code TransferRequestMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:TransferRequestMessage)
                TransferRequestProto.TransferRequestMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TransferRequestProto.internal_static_TransferRequestMessage_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetHeaders();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutableHeaders();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TransferRequestProto.internal_static_TransferRequestMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TransferRequestProto.TransferRequestMessage.class, TransferRequestProto.TransferRequestMessage.Builder.class);
            }

            // Construct using TransferRequestProto.TransferRequestMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                uuid_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                method_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                url_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                internalGetMutableHeaders().clear();
                body_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TransferRequestProto.internal_static_TransferRequestMessage_descriptor;
            }

            @java.lang.Override
            public TransferRequestProto.TransferRequestMessage getDefaultInstanceForType() {
                return TransferRequestProto.TransferRequestMessage.getDefaultInstance();
            }

            @java.lang.Override
            public TransferRequestProto.TransferRequestMessage build() {
                TransferRequestProto.TransferRequestMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public TransferRequestProto.TransferRequestMessage buildPartial() {
                TransferRequestProto.TransferRequestMessage result = new TransferRequestProto.TransferRequestMessage(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.uuid_ = uuid_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.method_ = method_;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.url_ = url_;
                result.headers_ = internalGetHeaders();
                result.headers_.makeImmutable();
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.body_ = body_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TransferRequestProto.TransferRequestMessage) {
                    return mergeFrom((TransferRequestProto.TransferRequestMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TransferRequestProto.TransferRequestMessage other) {
                if (other == TransferRequestProto.TransferRequestMessage.getDefaultInstance()) return this;
                if (other.hasUuid()) {
                    bitField0_ |= 0x00000001;
                    uuid_ = other.uuid_;
                    onChanged();
                }
                if (other.hasMethod()) {
                    bitField0_ |= 0x00000002;
                    method_ = other.method_;
                    onChanged();
                }
                if (other.hasUrl()) {
                    bitField0_ |= 0x00000004;
                    url_ = other.url_;
                    onChanged();
                }
                internalGetMutableHeaders().mergeFrom(
                        other.internalGetHeaders());
                if (other.hasBody()) {
                    setBody(other.getBody());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasUuid()) {
                    return false;
                }
                if (!hasMethod()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TransferRequestProto.TransferRequestMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TransferRequestProto.TransferRequestMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object uuid_ = "";

            /**
             * <code>required string uuid = 1;</code>
             */
            public boolean hasUuid() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required string uuid = 1;</code>
             */
            public java.lang.String getUuid() {
                java.lang.Object ref = uuid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        uuid_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string uuid = 1;</code>
             */
            public com.google.protobuf.ByteString
            getUuidBytes() {
                java.lang.Object ref = uuid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    uuid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string uuid = 1;</code>
             */
            public Builder setUuid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                uuid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string uuid = 1;</code>
             */
            public Builder clearUuid() {
                bitField0_ = (bitField0_ & ~0x00000001);
                uuid_ = getDefaultInstance().getUuid();
                onChanged();
                return this;
            }

            /**
             * <code>required string uuid = 1;</code>
             */
            public Builder setUuidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                uuid_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object method_ = "";

            /**
             * <code>required string method = 2;</code>
             */
            public boolean hasMethod() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>required string method = 2;</code>
             */
            public java.lang.String getMethod() {
                java.lang.Object ref = method_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        method_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string method = 2;</code>
             */
            public com.google.protobuf.ByteString
            getMethodBytes() {
                java.lang.Object ref = method_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    method_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string method = 2;</code>
             */
            public Builder setMethod(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                method_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string method = 2;</code>
             */
            public Builder clearMethod() {
                bitField0_ = (bitField0_ & ~0x00000002);
                method_ = getDefaultInstance().getMethod();
                onChanged();
                return this;
            }

            /**
             * <code>required string method = 2;</code>
             */
            public Builder setMethodBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                method_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object url_ = "";

            /**
             * <code>optional string url = 3;</code>
             */
            public boolean hasUrl() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public java.lang.String getUrl() {
                java.lang.Object ref = url_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        url_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public com.google.protobuf.ByteString
            getUrlBytes() {
                java.lang.Object ref = url_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    url_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public Builder setUrl(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                url_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public Builder clearUrl() {
                bitField0_ = (bitField0_ & ~0x00000004);
                url_ = getDefaultInstance().getUrl();
                onChanged();
                return this;
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public Builder setUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                url_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> headers_;

            private com.google.protobuf.MapField<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>
            internalGetHeaders() {
                if (headers_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            HeadersDefaultEntryHolder.defaultEntry);
                }
                return headers_;
            }

            private com.google.protobuf.MapField<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>
            internalGetMutableHeaders() {
                onChanged();
                ;
                if (headers_ == null) {
                    headers_ = com.google.protobuf.MapField.newMapField(
                            HeadersDefaultEntryHolder.defaultEntry);
                }
                if (!headers_.isMutable()) {
                    headers_ = headers_.copy();
                }
                return headers_;
            }

            public int getHeadersCount() {
                return internalGetHeaders().getMap().size();
            }

            /**
             * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
             */

            public boolean containsHeaders(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetHeaders().getMap().containsKey(key);
            }

            /**
             * Use {@link #getHeadersMap()} instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> getHeaders() {
                return getHeadersMap();
            }

            /**
             * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
             */

            public java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> getHeadersMap() {
                return internalGetHeaders().getMap();
            }

            /**
             * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
             */

            public TransferRequestProto.TransferRequestMessage.ListString getHeadersOrDefault(
                    java.lang.String key,
                    TransferRequestProto.TransferRequestMessage.ListString defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> map =
                        internalGetHeaders().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
             */

            public TransferRequestProto.TransferRequestMessage.ListString getHeadersOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> map =
                        internalGetHeaders().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearHeaders() {
                internalGetMutableHeaders().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
             */

            public Builder removeHeaders(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableHeaders().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString>
            getMutableHeaders() {
                return internalGetMutableHeaders().getMutableMap();
            }

            /**
             * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
             */
            public Builder putHeaders(
                    java.lang.String key,
                    TransferRequestProto.TransferRequestMessage.ListString value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableHeaders().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <code>map&lt;string, .TransferRequestMessage.ListString&gt; headers = 4;</code>
             */

            public Builder putAllHeaders(
                    java.util.Map<java.lang.String, TransferRequestProto.TransferRequestMessage.ListString> values) {
                internalGetMutableHeaders().getMutableMap()
                        .putAll(values);
                return this;
            }

            private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes body = 5;</code>
             */
            public boolean hasBody() {
                return ((bitField0_ & 0x00000010) != 0);
            }

            /**
             * <code>optional bytes body = 5;</code>
             */
            public com.google.protobuf.ByteString getBody() {
                return body_;
            }

            /**
             * <code>optional bytes body = 5;</code>
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                body_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes body = 5;</code>
             */
            public Builder clearBody() {
                bitField0_ = (bitField0_ & ~0x00000010);
                body_ = getDefaultInstance().getBody();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:TransferRequestMessage)
        }

        // @@protoc_insertion_point(class_scope:TransferRequestMessage)
        private static final TransferRequestProto.TransferRequestMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TransferRequestProto.TransferRequestMessage();
        }

        public static TransferRequestProto.TransferRequestMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<TransferRequestMessage>
                PARSER = new com.google.protobuf.AbstractParser<TransferRequestMessage>() {
            @java.lang.Override
            public TransferRequestMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TransferRequestMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TransferRequestMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TransferRequestMessage> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public TransferRequestProto.TransferRequestMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TransferRequestMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TransferRequestMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TransferRequestMessage_HeadersEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TransferRequestMessage_HeadersEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TransferRequestMessage_ListString_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TransferRequestMessage_ListString_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\032TransferRequestProto.proto\"\370\001\n\026Transfe" +
                        "rRequestMessage\022\014\n\004uuid\030\001 \002(\t\022\016\n\006method\030" +
                        "\002 \002(\t\022\013\n\003url\030\003 \001(\t\0225\n\007headers\030\004 \003(\0132$.Tr" +
                        "ansferRequestMessage.HeadersEntry\022\014\n\004bod" +
                        "y\030\005 \001(\014\032R\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\0221\n\005" +
                        "value\030\002 \001(\0132\".TransferRequestMessage.Lis" +
                        "tString:\0028\001\032\032\n\nListString\022\014\n\004pojo\030\001 \003(\t"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_TransferRequestMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_TransferRequestMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TransferRequestMessage_descriptor,
                new java.lang.String[]{"Uuid", "Method", "Url", "Headers", "Body",});
        internal_static_TransferRequestMessage_HeadersEntry_descriptor =
                internal_static_TransferRequestMessage_descriptor.getNestedTypes().get(0);
        internal_static_TransferRequestMessage_HeadersEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TransferRequestMessage_HeadersEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_TransferRequestMessage_ListString_descriptor =
                internal_static_TransferRequestMessage_descriptor.getNestedTypes().get(1);
        internal_static_TransferRequestMessage_ListString_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TransferRequestMessage_ListString_descriptor,
                new java.lang.String[]{"Pojo",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
